# Travis-CI Build for libgit2sharp
# see travis-ci.org for details

language: csharp
dist: xenial
dotnet: 2.1.506
mono: none
osx_image: xcode8.3

os:
 - osx
 - linux

before_install:
 - date -u
 - uname -a
 - env | sort

install:
 - git fetch --unshallow

# Build libgit2, LibGit2Sharp and run the tests
script:
 - ./buildandtest.sh 'LEAKS_IDENTIFYING'

# Only watch the development branch
branches:
 only:
   - master
   - /^maint.*/

# Notify of build changes
notifications:
 email:
  - emeric.fermas@gmail.com
