trigger:
- master
- maint/*

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

jobs:
- job: Windows
  pool:
    vmImage: 'VS2017-Win2016'
  steps:
  - script: buildandtest.cmd
- job: Linux
  pool:
    vmImage: 'Ubuntu 16.04'
  steps:
  - script: ./buildandtest.sh
- job: macOS
  pool:
    vmImage: 'macOS 10.13'
  steps:
  - script: ./buildandtest.sh
